# Generated by Django 3.0 on 2021-12-23 10:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20211223_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemetting',
            name='from_metting_time',
        ),
        migrations.RemoveField(
            model_name='schedulemetting',
            name='metting_date',
        ),
        migrations.RemoveField(
            model_name='schedulemetting',
            name='to_metting_time',
        ),
        migrations.AddField(
            model_name='schedulemetting',
            name='from_metting_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 10, 0, 26, 153546)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulemetting',
            name='to_meeting_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
