# Generated by Django 3.0 on 2021-12-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20211223_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemetting',
            old_name='from_metting_date_time',
            new_name='from_meeting_date_time',
        ),
    ]
