# Generated by Django 3.0 on 2021-12-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20211223_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemetting',
            old_name='metting_time_interval',
            new_name='meeting_time_interval',
        ),
    ]
